### ISSUE TITLE
[F] Analyse details

### ISSUE THREAD

**Issue by nikon-petr** [nikon-petr/angio#10]
***access:*** has permissions: ANALYSE_VIEW
***path:*** /analyse/{id}
***api paths:***

- /api/v2/analyse/{id}
- /api/v2/analyse/additional-info
- /api/v2/analyse/starred
- /api/v2/analyse/{id}/report
- /api/v2/analyse/{id}/archive
- /api/v2/analyse/{id}/geometric/vessel/{vesselId}

##### Todo
- [x] title (name and patient info)
- [x] data block: analyse info and original image
- [x] actions: delete, print, download archive, add conclusion, starred
- [x] conclusion
- [x] tab menu
- [x] bloodflow analyse tab
- [x] geometric analyse tab

**Comment by nikon-petr** [comment]
Add title and view configuration in https://github.com/nikon-petr/angio/commit/02535c8799ce575d72f2f5e44927135f57b58cf6
