### ISSUE TITLE
[F] Admin dashboard

### ISSUE THREAD

**Issue by nikon-petr** [nikon-petr/angio#14]
##### Todo
- [ ] analyse: total count
- [ ] analyse: total failed count + percent
- [ ] analyse: total success count + percent
- [ ] user: count
- [ ] organization: count
- [ ] button delete analyses
- [ ] button delete files in analyses
